### ISSUE TITLE
Multi-channel mix ends up distorted/staticky

### ISSUE THREAD

**Issue by c0bra** [AlexPl3331/node-audio-mixer#17]
I am trying to merge real time system audio with mic audio in an Electron.

All audio sounds fine when there's one input, but with two it gets distorted and staticky. I've checked all the bit depths and sample rates and they should all be matching.

If I try to change the mixer to two channel the pitch lowers and playback rate seems slower so I'm not sure multi-channel is working as expected.

Any ideas?

**Comment by AlexPl3331** [comment]
Hello, could you please provide me with:

1. Version of node.js
2. Version of Electron
3. Example code that repeats your problem

**Comment by c0bra** [comment]
> Hello, could you please provide me with:
> 
> 1. Version of node.js
> 2. Version of Electron
> 3. Example code that repeats your problem

I will try.  Will have to redo my streaming setup to make it stand-alone.  Hopefully by Monday.

**Comment by c0bra** [comment]
@AlexPl3331 OK got it: https://github.com/c0bra/node-audio-mixer-example

I can do a more robust example given more time. In my other code when I go down to a single input the resulting audio is fine but I'm not able to recreate that with this streaming method atm.

**Comment by AlexPl3331** [comment]
> @AlexPl3331 OK got it: https://github.com/c0bra/node-audio-mixer-example

Thanks for the example, I looked at it. Sorry, but the audio mixer doesn't support float32. About "if I plan to add support for float32"? I think I will try.

**Comment by c0bra** [comment]
Ah interesting. I didn't have luck capturing Int16 frames on a mac with ScreenCaptureKit. Perhaps I can do some on the fly processing to convert. I've done that elsewhere:

`const int16array = Int16Array.from(interleaved.map(x => (x > 0 ? x * 0x7FFF : x * 0x8000)));`

**Comment by AlexPl3331** [comment]
@c0bra
I’ve added support for float PCM and retested your example; it works as expected. Please update the package to version 2.1.0 and enable the "float" parameter in AudioMixer and/or AudioInput (where you use float). If the problem persists, feel free to reply here or open a new issue.
